### ISSUE TITLE
Error While installing ssh-executor

### ISSUE THREAD

**Issue by wjozefssrf** [bakharevpavel/ssh-executor#1]
Already done without errors :
$ sudo apt-get install libssh2-1-dev
$ npm install -g node-gyp

and when i wana install ssh-executor i get this error
## npm install ssh-executor --save

> ssh-executor@0.0.5 install /root/node/workshop/node_modules/ssh-executor
> node-gyp rebuild

make: Entering directory '/root/Downloads/interface_version1/node_modules/ssh-executor/build'
  CXX(target) Release/obj.target/ssh-executor/src/ssh-executor.o
../src/ssh-executor.cpp: In function ‘void connect(const v8::FunctionCallbackInfov8::Value&)’:
../src/ssh-executor.cpp:49:19: warning: ISO C++ forbids converting a string constant to ‘char_’ [-Wwrite-strings]
     char *error = "";
                   ^
../src/ssh-executor.cpp:67:15: warning: ISO C++ forbids converting a string constant to ‘char_’ [-Wwrite-strings]
         error = "Failed to connect.";
               ^
../src/ssh-executor.cpp:79:19: warning: ISO C++ forbids converting a string constant to ‘char_’ [-Wwrite-strings]
             error = "Failed to connect. Login data may be wrong.";
                   ^
../src/ssh-executor.cpp:86:17: warning: comparison with string literal results in unspecified behaviour [-Waddress]
     if(error == "") {
                 ^
../src/ssh-executor.cpp: In function ‘void exec(const v8::FunctionCallbackInfov8::Value&)’:
../src/ssh-executor.cpp:95:19: warning: ISO C++ forbids converting a string constant to ‘char_’ [-Wwrite-strings]
     char _error = "";
                   ^
../src/ssh-executor.cpp:112:19: warning: ISO C++ forbids converting a string constant to ‘char_’ [-Wwrite-strings]
             error = "Error while executing command.";
                   ^
../src/ssh-executor.cpp:139:17: warning: comparison with string literal results in unspecified behaviour [-Waddress]
     if(error != "") {
                 ^
  SOLINK_MODULE(target) Release/obj.target/ssh-executor.node
  COPY Release/ssh-executor.node
make: Leaving directory '/root/node/workshop/node_modules/ssh-executor/build'
ssh-executor@0.0.5 node_modules/ssh-executor

**Comment by chun-baoluo** [comment]
Thank you for your feeedback! "Error" words you see are parts of the C++ code and not compilation errors. In case of an actual error npm itself would notify you about it and abort the installation process.  Judging by npm log you posted, your ssh-executor installation completed successfully.
